In [1]:
import pandas as pd
import json

# Processing Match Summary

In [2]:
with open('RawData/wpl_matchSummary_2k23.json') as f:
    data = json.load(f)

df_matchSummary = pd.DataFrame(data)
df_matchSummary.head()

,team1,team2,winner,margin,ground,matchDate,scorecard
0,GG Women,MI Women,MI Women,143 runs,DY Patil,"Mar 4, 2023",WPL #1
1,RCB Women,DC Women,DC Women,60 runs,Brabourne,"Mar 5, 2023",WPL #2
2,UPW Women,GG Women,UPW Women,3 wickets,DY Patil,"Mar 5, 2023",WPL #3
3,MI Women,RCB Women,MI Women,9 wickets,Brabourne,"Mar 6, 2023",WPL #4
4,DC Women,UPW Women,DC Women,42 runs,DY Patil,"Mar 7, 2023",WPL #5

In [3]:
df_matchSummary.shape

(22, 7)

In [4]:
df_matchSummary.rename({'scorecard': 'match_id'}, axis = 1, inplace = True)
df_matchSummary.head()

       team1      team2     winner     margin     ground    matchDate match_id
0   GG Women   MI Women   MI Women   143 runs   DY Patil  Mar 4, 2023   WPL #1
1  RCB Women   DC Women   DC Women    60 runs  Brabourne  Mar 5, 2023   WPL #2
2  UPW Women   GG Women  UPW Women  3 wickets   DY Patil  Mar 5, 2023   WPL #3
3   MI Women  RCB Women   MI Women  9 wickets  Brabourne  Mar 6, 2023   WPL #4
4   DC Women  UPW Women   DC Women    42 runs   DY Patil  Mar 7, 2023   WPL #5

In [5]:
match_ids = {}

for index, row in df_matchSummary.iterrows():
    key1 = row['team1'] + ' Vs ' + row['team2']
    key2 = row['team2'] + ' Vs ' + row['team1']
    match_ids[key1] = row['match_id']
    match_ids[key2] = row['match_id']

In [6]:
match_ids

{'GG Women Vs MI Women': 'WPL #12',
 'MI Women Vs GG Women': 'WPL #12',
 'RCB Women Vs DC Women': 'WPL #11',
 'DC Women Vs RCB Women': 'WPL #11',
 'UPW Women Vs GG Women': 'WPL #17',
 'GG Women Vs UPW Women': 'WPL #17',
 'MI Women Vs RCB Women': 'WPL #19',
 'RCB Women Vs MI Women': 'WPL #19',
 'DC Women Vs UPW Women': 'WPL #20',
 'UPW Women Vs DC Women': 'WPL #20',
 'GG Women Vs RCB Women': 'WPL #16',
 'RCB Women Vs GG Women': 'WPL #16',
 'DC Women Vs MI Women': 'WPL #22',
 'MI Women Vs DC Women': 'WPL #22',
 'RCB Women Vs UPW Women': 'WPL #13',
 'UPW Women Vs RCB Women': 'WPL #13',
 'GG Women Vs DC Women': 'WPL #14',
 'DC Women Vs GG Women': 'WPL #14',
 'UPW Women Vs MI Women': 'WPL #21',
 'MI Women Vs UPW Women': 'WPL #21'}

In [7]:
df_matchSummary.to_csv('ProcessedData/pre_prcs_match_summary.csv', index = False)

# Processing Batting Summary

In [8]:
with open('RawData/wpl_battingSummary_2k23.json') as f:
    data = json.load(f)
  
df_battingSummary = pd.DataFrame(data)
df_battingSummary.head()

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR
0,MI Women Vs GG Women,MI Women,1,Yastika Bhatia †,c Wareham b Kanwar,1,8,0,0,12.50
1,MI Women Vs GG Women,MI Women,2,Hayley Matthews,b Gardner,47,31,3,4,151.61
2,MI Women Vs GG Women,MI Women,3,Nat Sciver-Brunt,c Rana b Wareham,23,18,5,0,127.77
3,MI Women Vs GG Women,MI Women,4,Harmanpreet Kaur (c),c Hemalatha b Rana,65,30,14,0,216.66
4,MI Women Vs GG Women,MI Women,5,Amelia Kerr,not out,45,24,6,1,187.50

In [9]:
def dismissal(dismissal):
    if dismissal == 'not out ' or dismissal == 'retired hurt ':
        return "not_out"
    else:
        return "out"

df_battingSummary['out/not_out'] = df_battingSummary.dismissal.apply(dismissal)

In [10]:
df_battingSummary['match_id'] = df_battingSummary['match'].map(match_ids)
df_battingSummary.head(20)

,match,teamInnings,battingPos,batsmanName,dismissal,runs,balls,4s,6s,SR,out/not_out,match_id
0,MI Women Vs GG Women,MI Women,1,Yastika Bhatia †,c Wareham b Kanwar,1,8,0,0,12.50,out,WPL #12
1,MI Women Vs GG Women,MI Women,2,Hayley Matthews,b Gardner,47,31,3,4,151.61,out,WPL #12
2,MI Women Vs GG Women,MI Women,3,Nat Sciver-Brunt,c Rana b Wareham,23,18,5,0,127.77,out,WPL #12
3,MI Women Vs GG Women,MI Women,4,Harmanpreet Kaur (c),c Hemalatha b Rana,65,30,14,0,216.66,out,WPL #12
4,MI Women Vs GG Women,MI Women,5,Amelia Kerr,not out,45,24,6,1,187.50,not_out,WPL #12
5,MI Women Vs GG Women,MI Women,6,Pooja Vastrakar,c Patel b Rana,15,8,3,0,187.50,out,WPL #12
6,MI Women Vs GG Women,MI Women,7,Issy Wong,not out,6,1,0,1,600.00,not_out,WPL #12
7,MI Women Vs GG Women,GG Women,1,Sabbhineni Meghana,b Nat Sciver-Brunt,2,4,0,0,50.00,out,WPL #12
8,MI Women Vs GG Women,GG Women,2,Beth Mooney (c)†,retired hurt,0,3,0,0,0.00,not_out,WPL #12
9,MI Women Vs GG Women,GG Women,3,Harleen Deol,c Wong b Nat Sciver-Brunt,0,2,0,0,0.00,out,WPL #12
10,MI Women Vs GG Women,GG Women,4,Ashleigh Gardner,c Matthews b Wong,0,1,0,0,0.00,out,WPL #12
11,MI Women Vs GG Women,GG Women,5,Annabel Sutherland,b Ishaque,6,14,0,0,42.85,out,WPL #12
12,MI Women Vs GG Women,GG Women,6,Dayalan Hemalatha,not out,29,23,1,2,126.08,not_out,WPL #12
13,MI Women Vs GG Women,GG Women,7,Georgia Wareham,b Ishaque,8,11,2,0,72.72,out,WPL #12
14,MI Women Vs GG Women,GG Women,8,Sneh Rana,lbw b Kerr,1,2,0,0,50.00,out,WPL #12
15,MI Women Vs GG Women,GG Women,9,Tanuja Kanwar,c Nat Sciver-Brunt b Kerr,0,3,0,0,0.00,out,WPL #12
16,MI Women Vs GG Women,GG Women,10,Mansi Joshi,lbw b Ishaque,6,19,0,0,31.57,out,WPL #12
17,MI Women Vs GG Women,GG Women,11,Monica Patel,b Ishaque,10,9,2,0,111.11,out,WPL #12
18,DC Women Vs RCB Women,DC Women,1,Meg Lanning (c),b Knight,72,43,14,0,167.44,out,WPL #11
19,DC Women Vs RCB Women,DC Women,2,Shafali Verma,c †Ghosh b Knight,84,45,10,4,186.66,out,WPL #11

In [11]:
df_battingSummary.drop(columns=["dismissal"], inplace=True)
df_battingSummary.head(10)

,match,teamInnings,battingPos,batsmanName,runs,balls,4s,6s,SR,out/not_out,match_id
0,MI Women Vs GG Women,MI Women,1,Yastika Bhatia †,1,8,0,0,12.50,out,WPL #12
1,MI Women Vs GG Women,MI Women,2,Hayley Matthews,47,31,3,4,151.61,out,WPL #12
2,MI Women Vs GG Women,MI Women,3,Nat Sciver-Brunt,23,18,5,0,127.77,out,WPL #12
3,MI Women Vs GG Women,MI Women,4,Harmanpreet Kaur (c),65,30,14,0,216.66,out,WPL #12
4,MI Women Vs GG Women,MI Women,5,Amelia Kerr,45,24,6,1,187.50,not_out,WPL #12
5,MI Women Vs GG Women,MI Women,6,Pooja Vastrakar,15,8,3,0,187.50,out,WPL #12
6,MI Women Vs GG Women,MI Women,7,Issy Wong,6,1,0,1,600.00,not_out,WPL #12
7,MI Women Vs GG Women,GG Women,1,Sabbhineni Meghana,2,4,0,0,50.00,out,WPL #12
8,MI Women Vs GG Women,GG Women,2,Beth Mooney (c)†,0,3,0,0,0.00,not_out,WPL #12
9,MI Women Vs GG Women,GG Women,3,Harleen Deol,0,2,0,0,0.00,out,WPL #12

In [12]:
df_battingSummary.shape

(336, 11)

In [13]:
df_battingSummary.to_csv('ProcessedData/pre_prcs_batting_summary.csv', index = False)

# Processing Bowling Summary

In [14]:
with open('RawData/wpl_bowlingSummary_2k23.json') as f:
    data = json.load(f)
  
df_bowlingSummary = pd.DataFrame(data)
df_bowlingSummary.head()

,match,bowlingTeam,bowlerName,overs,maiden,runs,wickets,economy,0s,4s,6s,wides,noBalls
0,MI Women Vs GG Women,MI Women,Ashleigh Gardner,4,0,38,1,9.50,7,7,0,0,0
1,MI Women Vs GG Women,MI Women,Mansi Joshi,2,0,17,0,8.50,7,2,1,1,0
2,MI Women Vs GG Women,MI Women,Tanuja Kanwar,2,0,12,1,6.00,6,2,0,0,0
3,MI Women Vs GG Women,MI Women,Monica Patel,2,0,34,0,17.00,1,7,0,2,0
4,MI Women Vs GG Women,MI Women,Georgia Wareham,3,0,30,1,10.00,6,4,1,0,0

In [15]:
df_bowlingSummary['match_id'] = df_bowlingSummary['match'].map(match_ids)
df_bowlingSummary.head()

,match,bowlingTeam,bowlerName,overs,maiden,runs,wickets,economy,0s,4s,6s,wides,noBalls,match_id
0,MI Women Vs GG Women,MI Women,Ashleigh Gardner,4,0,38,1,9.50,7,7,0,0,0,WPL #12
1,MI Women Vs GG Women,MI Women,Mansi Joshi,2,0,17,0,8.50,7,2,1,1,0,WPL #12
2,MI Women Vs GG Women,MI Women,Tanuja Kanwar,2,0,12,1,6.00,6,2,0,0,0,WPL #12
3,MI Women Vs GG Women,MI Women,Monica Patel,2,0,34,0,17.00,1,7,0,2,0,WPL #12
4,MI Women Vs GG Women,MI Women,Georgia Wareham,3,0,30,1,10.00,6,4,1,0,0,WPL #12

In [16]:
df_bowlingSummary.shape

(270, 14)

In [17]:
df_bowlingSummary.to_csv('ProcessedData/pre_prcs_bowling_summary.csv', index = False)

# Processing Player Summary

In [18]:
with open('RawData/wpl_playerInfo_df_2k23.json') as f:
    data = json.load(f)

df_playerSummary = pd.DataFrame(data)
df_playerSummary.head()

,playerName,team,battingStyle,bowlingStyle,playingRole
0,Meg Lanning,Delhi Capitals Women,Right hand Bat,Right arm Medium,Top order Batter
1,Taniya Bhatia,Delhi Capitals Women,Right hand Bat,None,Wicketkeeper Batter
2,Alice Capsey,Delhi Capitals Women,Right hand Bat,Right arm Offbreak,Batting Allrounder
3,Laura Harris,Delhi Capitals Women,Right hand Bat,None,Top order Batter
4,Jasia Akhtar,Delhi Capitals Women,Right hand Bat,Right arm Medium,

In [19]:
df_playerSummary.shape

(90, 5)

In [20]:
df_playerSummary[df_playerSummary['team'] == 'Royal Challengers Bangalore Women  ']

,playerName,team,battingStyle,bowlingStyle,playingRole
55,Smriti Mandhana,Royal Challengers Bangalore Women,Left hand Bat,Right arm Offbreak,Opening Batter
56,Kanika Ahuja,Royal Challengers Bangalore Women,Left hand Bat,Right arm Offbreak,Allrounder
57,Sobhana Asha,Royal Challengers Bangalore Women,Right hand Bat,Legbreak Googly,Allrounder
58,Erin Burns,Royal Challengers Bangalore Women,Right hand Bat,Right arm Offbreak,Allrounder
59,Sophie Devine,Royal Challengers Bangalore Women,Right hand Bat,Right arm Medium,Batting Allrounder
60,Richa Ghosh,Royal Challengers Bangalore Women,Right hand Bat,Right arm Medium,Wicketkeeper Batter
61,Disha Kasat,Royal Challengers Bangalore Women,Right hand Bat,Right arm Medium fast,Middle order Batter
62,Poonam Khemnar,Royal Challengers Bangalore Women,Right hand Bat,Legbreak,
63,Heather Knight,Royal Challengers Bangalore Women,Right hand Bat,Right arm Offbreak,Middle order Batter
64,Shreyanka Patil,Royal Challengers Bangalore Women,Right hand Bat,Right arm Offbreak,Allrounder
65,Sahana Pawar,Royal Challengers Bangalore Women,Right hand Bat,Slow Left arm Orthodox,Bowler
66,Ellyse Perry,Royal Challengers Bangalore Women,Right hand Bat,Right arm Fast medium,Allrounder
67,Preeti Bose,Royal Challengers Bangalore Women,Right hand Bat,Slow Left arm Orthodox,Bowler
68,Renuka Singh,Royal Challengers Bangalore Women,Right hand Bat,Right arm Medium fast,Bowler
69,Indrani Roy,Royal Challengers Bangalore Women,Right hand Bat,Right arm Medium fast,Wicketkeeper Batter
70,Megan Schutt,Royal Challengers Bangalore Women,Right hand Bat,Right arm Fast medium,Bowler
71,Dane van Niekerk,Royal Challengers Bangalore Women,Right hand Bat,Legbreak,Allrounder
72,Komal Zanzad,Royal Challengers Bangalore Women,Right hand Bat,Left arm Medium fast,Bowler

In [21]:
df_playerSummary.to_csv('ProcessedData/pre_prcs_player_summary.csv', index = False)